install:
  - ruby --version
  - gem --version
  - gem install bundler
  - bundler --version
  - bundle install
  - cinst ansicon

test_script:
  - rake username=edu161 key=w6ZgKtUCziNu5fzV4RNa

environment:
  matrix:
    - ruby_version: '18'
    - ruby_version: '19'
    - ruby_version: '20'
    - ruby_version: '21'
    - ruby_version: '22'
