
install:
  - SET PATH=C:\Ruby21\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler
  - bundler --version
  - bundle install
  - cinst ansicon
  - rake username=edu161 key=w6ZgKtUCziNu5fzV4RNa

